# Global
WIDTH, HEIGHT = 700, 900
GREEN = (0, 230, 0)
FONT_SIZE = 25

# Player
PLAYER_SIZE = (36, 24)
PLAYER_POS = (WIDTH // 2, HEIGHT - 128)
PLAYER_SPEED = 128

# Shield
SHIELD_SIZE = (64, 52)
NUM_SHIELDS = 4
SPACE_BETWEEN = 150
SHIELD_MARGIN_X = 100
SHIELD_MARGIN_Y = HEIGHT - 220

# --- BOTTOM HUD ---
BOTTOM_HUD_HEIGHT = 60
BOTTOM_HUD_MARGIN_X = 30
BOTTOM_HUD_Y = HEIGHT - BOTTOM_HUD_HEIGHT
BOTTOM_HUD_PADDING_Y = 4

# Line
LINE_WIDTH = 2
LINE_POS = (0, BOTTOM_HUD_Y)

# Lives
LIVES_TEXT_POS = (BOTTOM_HUD_MARGIN_X, BOTTOM_HUD_Y + BOTTOM_HUD_PADDING_Y)

SHIP_IMG_SIZE = (36, 24)
SHIP_IMG_POS = (LIVES_TEXT_POS[0] + 50, BOTTOM_HUD_Y + BOTTOM_HUD_PADDING_Y)
SHIP_IMG_OFFSET = 45

# Credit
CREDIT_TEXT_POS = (WIDTH - BOTTOM_HUD_MARGIN_X, BOTTOM_HUD_Y + BOTTOM_HUD_PADDING_Y)

# --- TOP HUD ---
TOP_HUD_HEIGHT = 60
TOP_HUD_MARGIN_X = 30
TOP_HUD_MARGIN_Y = 15
TEXT_SCORE_PADDING = 15

# Score<1>
TEXT_SCORE_1_POS = (TOP_HUD_MARGIN_X, TOP_HUD_MARGIN_Y)

# High score
TEXT_HIGH_SCORE_POS = (WIDTH // 2, TOP_HUD_MARGIN_Y)

# Score<2>
TEXT_SCORE_2_POS = (WIDTH - TOP_HUD_MARGIN_X, TOP_HUD_MARGIN_Y)