# Global
WIDTH, HEIGHT = 700, 900
GREEN = (0, 230, 0)

# Player
PLAYER_SIZE = (36, 24)
PLAYER_POS = (WIDTH // 2, HEIGHT - 128)
PLAYER_SPEED = 128

# Shield
SHIELD_SIZE = (64, 52)
NUM_SHIELDS = 4
SPACE_BETWEEN = 150
SHIELD_MARGIN_X = 100
SHIELD_MARGIN_Y = HEIGHT - 220

# --- BOTTOM HUD ---
BOTTOM_HUD_HEIGHT = 60
HUD_MARGIN_X = 30
HUD_BOTTOM_Y = HEIGHT - BOTTOM_HUD_HEIGHT
HUD_PADDING_Y = 4

# Line
LINE_WIDTH = 2
LINE_POS = (0, HUD_BOTTOM_Y)

# Lives
LIVES_TEXT_POS = (HUD_MARGIN_X, HUD_BOTTOM_Y + HUD_PADDING_Y)

SHIP_IMG_SIZE = (36, 24)
SHIP_IMG_POS = (LIVES_TEXT_POS[0] + 50, HUD_BOTTOM_Y + HUD_PADDING_Y)
SHIP_IMG_OFFSET = 45

# Credit
CREDIT_TEXT_POS = (WIDTH - HUD_MARGIN_X , HUD_BOTTOM_Y + HUD_PADDING_Y)